export const ADD_10_ROWS = "ADD_10_ROWS";
export const ADD_COLUMN = "ADD_COLUMN";
export const CHANGE_ATTRIBUTE = "CHANGE_ATTRIBUTE";
export const CHANGE_CELL = "CHANGE_CELL";
export const CLEAR_SPREADSHEET = "CLEAR_SPREADSHEET";